CREATE DATABASE IF NOT EXISTS local_service_finder;
USE local_service_finder;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('USER','PROVIDER','ADMIN') NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  category VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  location VARCHAR(255) NOT NULL,
  provider_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_services_provider FOREIGN KEY (provider_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  service_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  service_date DATE NOT NULL,
  notes VARCHAR(1000) NOT NULL,
  status ENUM('PENDING','APPROVED','DECLINED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bookings_service FOREIGN KEY (service_id) REFERENCES services(id),
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id)
);
ALTER TABLE bookings
DROP FOREIGN KEY fk_bookings_service;

ALTER TABLE bookings
ADD CONSTRAINT fk_bookings_service
FOREIGN KEY (service_id)
REFERENCES services(id)
ON DELETE CASCADE;
ALTER TABLE bookings
DROP FOREIGN KEY FKjcwbou2jlblfwu14uoxs65b25;
ALTER TABLE bookings
ADD CONSTRAINT FK_bookings_service
FOREIGN KEY (service_id)
REFERENCES services(id)
ON DELETE CASCADE;
ALTER TABLE bookings 
MODIFY COLUMN status 
ENUM('PENDING','APPROVED','DECLINED','CONFIRMED');