spring.application.name=local-service-finder-backend

# ================= SERVER =================
server.address=0.0.0.0
server.port=${PORT:${SERVER_PORT:8080}}
server.forward-headers-strategy=framework

# ================= DATABASE (POSTGRESQL) =================
spring.datasource.url=jdbc:postgresql://dpg-d737e315pdvs73f953g0-a:5432/servicehub_8afx?sslmode=require&user=servicehub_8afx_user&password=o506MiHmeuO7cROLvZBMeOj2wyevJHNm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ================= JPA =================
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ================= APP CONFIG =================
app.allowed-origins=${FRONTEND_URL:}

# ================= JWT =================
app.jwt.secret=${JWT_SECRET:}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ================= ADMIN =================
app.admin.name=${APP_ADMIN_NAME:System Admin}
app.admin.email=${APP_ADMIN_EMAIL:admin@localservice.com}
app.admin.password=${APP_ADMIN_PASSWORD:Admin@123}
app.demo.user.email=${DEMO_USER_EMAIL:user@demo.com}
app.demo.user.password=${DEMO_USER_PASSWORD:User@123}
app.demo.provider.email=${DEMO_PROVIDER_EMAIL:provider@demo.com}
app.demo.provider.password=${DEMO_PROVIDER_PASSWORD:Provider@123}
app.demo.admin.email=${DEMO_ADMIN_EMAIL:admin@demo.com}
app.demo.admin.password=${DEMO_ADMIN_PASSWORD:Admin@123}
